name: Issue Report
description: File a bug report
title: "[Issue]: "
labels: [bug, triage, unverified]
body:
  - type: markdown
    attributes:
      value: |
        > Please be sure to read our full guidelines for submitting issues on this repo's homepage before you continue.
  - type: markdown
    attributes:
      value: |
        # Basic Information
  - type: textarea
    id: details
    attributes:
      label: Describe the Issue in Detail
      description: A clear and concise description of the issue.
    validations:
      required: true
  - type: checkboxes
    id: reproduction-apps
    attributes:
      label: Can reproduce in
      description: Which of our demo apps have you reproduced this issue in?
      options:
        - label: Community App
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions on how to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Tap on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true
  - type: textarea
    id: screenshots-video
    attributes:
      label: Screenshots or Videos
      description: Please add screenshots and/or videos to help explain your problem.
    validations:
      required: true
  - type: textarea
    id: reproduction-tvml
    attributes:
      label: Reproduction TVML
      description: If applicable, please provide the TVML to reproduce the issue.
      render: xml
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # Environment Information
  - type: input
    id: tv-shell-version
    attributes:
      label: TV Shell Version
      description: The version of the Rock for Apple TV Shell (e.g. v2.0).
    validations:
      required: true
  - type: input
    id: last-known-working-version
    attributes:
      label: Last Known Working Version
      description: If applicable, what version of the shell last worked correctly?
    validations:
      required: false
  - type: input
    id: ios-info
    attributes:
      label: Device Type(s) and TVOS Version(s)
      description: What hardware devices and TVOS versions are experiencing the issue?
      placeholder: 
    validations:
      required: true
